### ISSUE TITLE
Some problems when installing (Pineapple MKIV)

### ISSUE THREAD

**Issue by p611148aadsl** [adde88/hostapd-mana-openwrt#3]
I try to install it on wifipineapple MKIV.
But when i install hostapd-mana.ipk,there is a problem

root@Pineapple:/usb# opkg -d usb install hostapd-mana_2.6-2_ar71xx.ipk 
Installing hostapd-mana (2.6-2) to usb...
Configuring asleap.
/usb//usr/lib/opkg/info/asleap.postinst: line 4: default_postinst: not found
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for hostapd-mana:
 * 	sslsplit * 
 * opkg_install_cmd: Cannot install package hostapd-mana.
 * pkg_run_script: package "asleap" postinst script returned status 127.
 * opkg_configure: asleap.postinst returned 127.

I have installed the dependencies:libubus, tinyproxy, stunnel, ip
And when i try to install sslstrip,there is a problem,too....
root@Pineapple:/usb# opkg -d usb install sslsplit_0.4.11-1_ar71xx.ipk 
Installing sslsplit (0.4.11-1) to usb...
Configuring asleap.
/usb//usr/lib/opkg/info/asleap.postinst: line 4: default_postinst: not found
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for sslsplit:
 * 	libcrypto * 
 * opkg_install_cmd: Cannot install package sslsplit.
 * pkg_run_script: package "asleap" postinst script returned status 127.
 * opkg_configure: asleap.postinst returned 127.

I search libcrypto in the list of opkg list .There is only libcryptoxx.And i install it,but i still miss libcrypto.
I don't know what to do....

**Comment by p611148aadsl** [comment]
And i can't use opkg update.
All dependencies are installed through downloading ipk...

**Comment by adde88** [comment]
First: i have only tested this on the 6.th generation Pineapples, though i know at least one person have gotten it to work on a MKIV.

Second: All error messages displaying something about "_postinst: not found_" can safely be ignored.

I highly suggest you get "_opkg update_" working, as opkg should download the dependencies itself when installing the package, as long as you use "_opkg update_" first.

Are you able to get "sslsplit" working by itself? Because that project has nothing to do with Mana Toolkit at all, it just so happens that Mana Toolkit uses it. But you should be able to run it without installing Mana.

SSLstrip+ is another story though. This gets installed as a part of the Mana Toolkit automatically. But it has no independent ipk that can be found on any public openwrt-repositories.
