### ISSUE TITLE
Openwrt cannot install some packages

### ISSUE THREAD

**Issue by hASVAN** [adde88/hostapd-mana-openwrt#5]
hello im trying to install hostapd-mana on Tp link mr3020 But when i try to install hostapd-mana_2.6-8_ar71xx.ipk ,there is a error

root@OpenWrt:~# opkg install hostapd-mana_2.6-8_ar71xx.ipk
Installing hostapd-mana (2.6-8) to root...
Configuring asleap.
//usr/lib/opkg/info/asleap.postinst: line 4: default_postinst: not found
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for hostapd-mana:
 *      sslsplit *
 * opkg_install_cmd: Cannot install package hostapd-mana.
 * pkg_run_script: package "asleap" postinst script returned status 127.
 * opkg_configure: asleap.postinst returned 127.

and I have installed the dependencies  libubus, tinyproxy, stunnel, ip but when i try to install sslstrip,there i get a error too

root@OpenWrt:~# opkg install asleap_2.2-1_ar71xx.ipk
Installing asleap (2.2-1) to root...
Configuring asleap.
//usr/lib/opkg/info/asleap.postinst: line 4: default_postinst: not found
Collected errors:
 * pkg_run_script: package "asleap" postinst script returned status 127.
 * opkg_configure: asleap.postinst returned 127.

**Comment by adde88** [comment]
The package you're trying to install is primarily built for the wifi pineapples, which explains why it's unable to complete the installation. Because sslsplit doesn't exist of the default openwrt repos.
You could force the install by adding "--force-depends" to opkg. But then you wouldn't be able to run sslsplit, and you would need to tweak the scripts because they again depend on it.

You could try checking out my repo. [link](https://github.com/adde88/openwrt-useful-tools) which contains sslplit. But i'm not sure if it would run on your device, as it's compiled for the Pineapples.
If not, you need to get sslsplit somehow to be able to take advatage of this package.

I have a lighter version [here](https://github.com/adde88/openwrt-useful-tools/tree/master/MANA), which i made so that people could get/build ONLY hostapd-mana for their devices. But then they would need to do alot of scripting by themselves, as creating something that would work flawlessly across all devices is very hard.

Regardig the last part of your issue:
`and I have installed the dependencies libubus, tinyproxy, stunnel, ip but when i try to install sslstrip,there i get a error too`

The output you're showing is from installing asleap. And the "error-message" you're getting can safely be ignored, as it's not an actual error causing the install to fail.
It's simply whining about the IPK not having a postinst script. Which it doesn't need.
